export const OBTENER_CONTACTOS = "OBTENER_CONTACTOS";
export const AGREGARCONTACTOS = "AGREGARCONTACTOS";
export const ACTUALIZARCONTACTOS = "ACTUALIZARCONTACTOS";
export const CANCELAR_ACTUALIZACION = "CANCELAR_ACTUALIZACION";
export const ELIMINARCONTACTOS = "ELIMINARCONTACTOS";
export const ELIMINADOLOGICO = "ELIMINADOLOGICO";
export const SELECCIONARCONTACTO = "SELECCIONARCONTACTO";
